[workspace]
members = [
    "variables_and_mutability",
    "variables_and_shadowing",
    "data_types",
    "functions",
    "control_flow",
    "understanding_ownership"
    # Add additional projects here
]